#Include Script_Base.ahk

; Interaction Configuration Section
KeyBindInteractionMenu := "m"
KeyBindEnter := "enter"
KeybindLeftArrow := "left"
KeybindRightArrow := "right"
KeyBindDownArrow := "down"
KeyBindUpArrow := "up"
KeyBindBackspace := "Backspace"
KeyBindF := "f"
KeybindE := "e"
KeyBindEscape := "escape"
KeybindSpace := "space"
KeybindExplode := "g"
KeyBindSwitchToStoryCharacter := "f6"

; Weapon Menu Configuration Section
KeyBindWeaponWheel := "tab"
KeyBindAimButton := "rbutton"
KeyBindShootButton := "lbutton"
KeyBindSprintButton := "lshift"
KeyBindSpecialWeapon := "5"
KeyBindHeavyWeapon := "4"
KeyBindSniper := "9"
KeyBindPistol := "6"
KeyBindMelee := "2"
KeyBindUnarmed := "1"
KeyBindNextWeapon := "wheeldown"
KeyBindPreviousWeapon := "wheelup"

; Movement Configuration
KeybindMoveForward := "w"
KeyBindMoveLeft := "a"
KeybindMoveBackward := "s"
KeyBindMoveRight := "d"
KeyBindLookBehind := "c"

; --- Keyboard Scancodes ---
global SC_Escape     := "SC001"
global SC_1          := "SC002"
global SC_2          := "SC003"
global SC_3          := "SC004"
global SC_4          := "SC005"
global SC_5          := "SC006"
global SC_6          := "SC007"
global SC_7          := "SC008"
global SC_8          := "SC009"
global SC_9          := "SC00A"
global SC_0          := "SC00B"

global SC_Tab        := "SC00F"
global SC_Q          := "SC010"
global SC_W          := "SC011"
global SC_E          := "SC012"
global SC_R          := "SC013"
global SC_T          := "SC014"
global SC_Z          := "SC015" ; (Y on QWERTY)
global SC_U          := "SC016"
global SC_I          := "SC017"
global SC_O          := "SC018"
global SC_P          := "SC019"

global SC_A          := "SC01E"
global SC_S          := "SC01F"
global SC_D          := "SC020"
global SC_F          := "SC021"
global SC_G          := "SC022"
global SC_H          := "SC023"
global SC_J          := "SC024"
global SC_K          := "SC025"
global SC_L          := "SC026"

global SC_LShift     := "SC02A"
global SC_Y          := "SC02C" ; (Z on QWERTY)
global SC_X          := "SC02D"
global SC_C          := "SC02E"
global SC_V          := "SC02F"
global SC_B          := "SC030"
global SC_N          := "SC031"
global SC_M          := "SC032"

global SC_LControl   := "SC01D"
global SC_LAlt       := "SC038"
global SC_Space      := "SC039"

global SC_F1         := "SC03B"
global SC_F2         := "SC03C"
global SC_F3         := "SC03D"
global SC_F4         := "SC03E"
global SC_F5         := "SC03F"
global SC_F6         := "SC040"
global SC_F7         := "SC041"
global SC_F8         := "SC042"

global SC_End        := "SC14F"
global SC_Delete     := "SC153"
global SC_Insert     := "SC152"
global SC_Home       := "SC147"
global SC_PageUp     := "SC149"
global SC_PageDown   := "SC151"
